### ISSUE TITLE
Header image isn't loading

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/AnVIL_Book_Instructor_Guide#77]
Not sure when this happened, but the header image isn't loading anymore.  I noticed it when I rendered locally today, but it's also missing from the live site.  Haven't looked into it at all yet, probably an easy fix.

**Comment by avahoffman** [comment]
Looking into this now.

**Comment by avahoffman** [comment]
See #78 

Looks like the image file was just deleted when the GHA rendered. Was not deleted on re-render, so not sure why this happened. Could just be a one time thing. Let's keep an eye on it..
